version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_list_api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - $PWD/static:/server/static
    restart: always
  mongo:
    image: mongo:4.4.3
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - $PWD/db:/data/db
    restart: always