version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: todo_list_api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - './:/opt/server:cached'
      - '$PWD/static:/server/static'
  mongo:
    image: mongo:4.4.3
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - $PWD/db:/data/db
    restart: always
  mongo_express:
      image: 'mongo-express:0.54.0'
      container_name: mongo_express
      depends_on:
          - 'mongo'
      ports:
          - '8081:8081'
      restart: always